# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       socam-notifier

# >> macros
# << macros

Summary:    Socam Notifier
Version:    1.0.0
Release:    1
Group:      Applications/Internet
License:    TBD
Source0:    %{name}-%{version}.tar.bz2
#Requires:  pkgconfig(QtCore) >= 4.7.0
#Requires:  pkgconfig(QtGui)
#Requires:  pkgconfig(QtWebKit)
#Requires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtGui)
Provides:   socam-notifier = 1.0.0

%description
Socam Notifier

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

qmake socam-notifier.pro

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
#%qmake_install
make install INSTALL_ROOT=%{buildroot}

mkdir -p %{buildroot}/opt/socam/socam-notifier/images
cp %{_builddir}/%{name}-%{version}/images/* %{buildroot}/opt/socam/socam-notifier/images

mkdir -p %{buildroot}/usr/share/applications/
cp %{_builddir}/%{name}-%{version}/socam-notifier.desktop %{buildroot}/usr/share/applications/

mkdir -p %{buildroot}/etc/socam
cp %{_builddir}/%{name}-%{version}/notifier.conf %{buildroot}/etc/socam

# >> install post
# << install post

# >> post

# << post

%files
%defattr(-,root,root,-)
/usr/bin/socam-notifier
/opt/socam/socam-notifier/images/*
/usr/share/applications/*
/etc/*

# >> files
# << files
